//! Renderer: compose small reusable string fragments into a standalone,
//! compilable application project.
//!
//! No `templates/<preset>/` copies of whole apps exist here. Every preset is
//! produced by the same fragment functions driven by the declarative
//! [`ResolvedSpec`](super::spec::ResolvedSpec): layout selects panel slots,
//! features select code sections. Same input always yields the same bytes
//! (no timestamps, fixed file order).

use super::model::Feature;
use super::spec::{ResolvedSpec, ScaffoldError};
use std::collections::BTreeSet;
use std::path::Path;

/// A generated file: project-relative path plus exact bytes.
pub struct GeneratedFile {
    pub path: &'static str,
    pub contents: String,
}

/// Render every project file in fixed order. Pure and deterministic.
pub fn render_project(spec: &ResolvedSpec) -> Vec<GeneratedFile> {
    vec![
        GeneratedFile {
            path: "Cargo.toml",
            contents: cargo_toml(spec),
        },
        GeneratedFile {
            path: "src/main.rs",
            contents: main_rs(spec),
        },
        GeneratedFile {
            path: "src/app.rs",
            contents: app_rs(spec),
        },
        GeneratedFile {
            path: "src/demo.rs",
            contents: demo_rs(spec),
        },
        GeneratedFile {
            path: ".scaffold.toml",
            contents: scaffold_toml(spec),
        },
        GeneratedFile {
            path: "AGENTS.md",
            contents: agents_md(spec),
        },
        GeneratedFile {
            path: "README.md",
            contents: readme_md(spec),
        },
    ]
}

/// Write the rendered project under `out_dir`, creating directories.
/// Fails before writing anything when `out_dir` already exists and is
/// non-empty, so generation never merges into an unrelated tree.
pub fn write_project(spec: &ResolvedSpec, out_dir: &Path) -> Result<(), ScaffoldError> {
    if out_dir.exists() {
        let non_empty = std::fs::read_dir(out_dir)
            .map_err(|err| {
                ScaffoldError(format!(
                    "cannot inspect output directory '{}': {err}",
                    out_dir.display()
                ))
            })?
            .next()
            .is_some();
        if non_empty {
            return Err(ScaffoldError(format!(
                "output directory '{}' already exists and is not empty. \
                 Remove it or pass --output-dir <empty-dir>.",
                out_dir.display()
            )));
        }
    }
    for file in render_project(spec) {
        let target = out_dir.join(file.path);
        if let Some(parent) = target.parent() {
            std::fs::create_dir_all(parent).map_err(|err| {
                ScaffoldError(format!(
                    "cannot create directory '{}': {err}",
                    parent.display()
                ))
            })?;
        }
        std::fs::write(&target, file.contents).map_err(|err| {
            ScaffoldError(format!("cannot write file '{}': {err}", target.display()))
        })?;
    }
    Ok(())
}

const SHELL_GIT_URL: &str = "https://github.com/JhonMA82/iced-desktop-shell";

fn has(spec: &ResolvedSpec, feature: Feature) -> bool {
    spec.has_feature(feature)
}

// ---------------------------------------------------------------------------
// Cargo.toml
// ---------------------------------------------------------------------------

fn shell_dependency(spec: &ResolvedSpec) -> String {
    match spec.shell_path.as_ref() {
        Some(path) => {
            format!("desktop-shell = {{ package = \"desktop-shell\", path = \"{path}\" }}")
        }
        None => {
            format!("desktop-shell = {{ package = \"desktop-shell\", git = \"{SHELL_GIT_URL}\" }}")
        }
    }
}

fn cargo_toml(spec: &ResolvedSpec) -> String {
    format!(
        "[package]\nname = \"{crate_name}\"\nversion = \"0.1.0\"\nedition = \"2024\"\n\
         \n[workspace]\n\
         \n[dependencies]\n{shell_dep}\niced = \"0.14\"\n",
        crate_name = spec.crate_name,
        shell_dep = shell_dependency(spec),
    )
}

// ---------------------------------------------------------------------------
// src/main.rs
// ---------------------------------------------------------------------------

fn main_rs(spec: &ResolvedSpec) -> String {
    format!(
        "//! {title} — technical desktop application entry point.\n\
         //!\n\
         //! Generated by the iced-desktop-shell scaffolder (layout: {layout}).\n\
         //! Normal, editable application code.\n\
         \n\
         mod app;\n\
         mod demo;\n\
         \n\
         use app::{{AppState, Message, update, view}};\n\
         use iced::event;\n\
         \n\
         fn main() -> iced::Result {{\n\
         \x20   iced::application(AppState::new, update, view)\n\
         \x20       .title(\"{title}\")\n\
         \x20       .theme(|state: &AppState| state.shell.theme.to_iced_theme())\n\
         \x20       .subscription(|_state: &AppState| {{\n\
         \x20           event::listen_with(|event, status, _window| Some(Message::Event(event, status)))\n\
         \x20       }})\n\
         \x20       .window(iced::window::Settings {{\n\
         \x20           size: iced::Size::new(1280.0, 800.0),\n\
         \x20           min_size: Some(iced::Size::new(800.0, 600.0)),\n\
         \x20           position: iced::window::Position::Centered,\n\
         \x20           ..Default::default()\n\
         \x20       }})\n\
         \x20       .run()\n\
         }}\n",
        title = spec.app_title,
        layout = spec.layout.kebab(),
    )
}

// ---------------------------------------------------------------------------
// src/app.rs
// ---------------------------------------------------------------------------

fn persist_stmt(spec: &ResolvedSpec) -> &'static str {
    if has(spec, Feature::Persistence) {
        "state.shell.request_save_preferences();"
    } else {
        ""
    }
}

fn any_panel(spec: &ResolvedSpec) -> bool {
    has(spec, Feature::Explorer) || has(spec, Feature::Inspector) || has(spec, Feature::BottomPanel)
}

fn app_rs(spec: &ResolvedSpec) -> String {
    let mut out = String::new();

    out.push_str(&format!(
        "//! {title} — application orchestrator (State / Message / Update / View).\n\
         //!\n\
         //! Generated by the iced-desktop-shell scaffolder (layout: {layout},\n\
         //! features: {features}).\n\
         //! Normal, editable application code: the generator is not needed to keep\n\
         //! developing this project.\n\
         \n",
        title = spec.app_title,
        layout = spec.layout.kebab(),
        features = spec.feature_list(),
    ));

    out.push_str("use crate::demo::{self, DemoMessage, DemoState};\n");
    out.push_str("use desktop_shell::ShellMessage;\n");
    out.push_str("use desktop_shell::command::CommandId;\n");
    if any_panel(spec) {
        out.push_str("use desktop_shell::panel::{PanelLocation, PanelState};\n");
    }
    out.push_str("use desktop_shell::theme::{ThemeMode, tokens};\n");
    out.push_str("use iced::keyboard::Event as KeyboardEvent;\n");
    out.push_str("use iced::widget::{Column, Row, button, container, text};\n");
    out.push_str("use iced::{Alignment, Element, Event, Length, Task};\n");
    out.push('\n');

    out.push_str(
        "/// Unified message type for the application.\n\
         #[derive(Debug, Clone)]\n\
         pub enum Message {\n\
         \x20   Shell(ShellMessage),\n\
         \x20   Demo(DemoMessage),\n\
         \x20   Event(Event, iced::event::Status),\n\
         }\n\
         \n\
         impl From<ShellMessage> for Message {\n\
         \x20   fn from(msg: ShellMessage) -> Self {\n\
         \x20       Self::Shell(msg)\n\
         \x20   }\n\
         }\n\
         \n\
         impl From<DemoMessage> for Message {\n\
         \x20   fn from(msg: DemoMessage) -> Self {\n\
         \x20       Self::Demo(msg)\n\
         \x20   }\n\
         }\n\
         \n\
         /// Top-level application state: reusable shell plus domain stub.\n\
         #[derive(Debug, Clone)]\n\
         pub struct AppState {\n\
         \x20   pub shell: desktop_shell::ShellState,\n\
         \x20   pub demo: DemoState,\n\
         }\n\
         \n",
    );

    // -- new() ---------------------------------------------------------------
    out.push_str(
        "impl AppState {\n\
         \x20   /// Boot constructor: pure assembly plus optional preference load.\n\
         \x20   pub fn new() -> (Self, Task<Message>) {\n\
         \x20       let mut shell = desktop_shell::ShellState::new();\n",
    );
    out.push_str(&format!(
        "\x20       shell.theme = {};\n",
        spec.theme.theme_mode()
    ));
    if has(spec, Feature::Explorer) {
        out.push_str(
            "\x20       shell.dock.register(PanelState::new(demo::LEFT_PANEL, demo::LEFT_TITLE, PanelLocation::Left, tokens::SIDEBAR_DEFAULT_WIDTH));\n",
        );
    }
    if has(spec, Feature::Inspector) {
        out.push_str(
            "\x20       shell.dock.register(PanelState::new(demo::RIGHT_PANEL, demo::RIGHT_TITLE, PanelLocation::Right, tokens::INSPECTOR_DEFAULT_WIDTH));\n",
        );
    }
    if has(spec, Feature::BottomPanel) {
        out.push_str(
            "\x20       shell.dock.register(PanelState::new(demo::BOTTOM_PANEL, demo::BOTTOM_TITLE, PanelLocation::Bottom, tokens::BOTTOM_PANEL_DEFAULT_HEIGHT));\n\
             \x20       shell.bottom_panel = desktop_shell::bottom_panel::BottomPanelState {\n\
                 \x20           active_tab: demo::BOTTOM_TITLE.to_string(),\n\
                 \x20           tabs: vec![demo::BOTTOM_TITLE.to_string()],\n\
                 \x20       };\n",
        );
    }
    out.push_str("\x20       demo::register_demo_commands(&mut shell.commands);\n");
    if has(spec, Feature::Ribbon) {
        out.push_str(
            "\x20       shell.ribbon_tabs = demo::ribbon_tabs();\n\
             \x20       if let Some(first_tab) = shell.ribbon_tabs.first() {\n\
             \x20           shell.active_ribbon_tab = first_tab.id.clone();\n\
             \x20       }\n",
        );
    }
    if has(spec, Feature::Persistence) {
        out.push_str("\x20       shell.load_preferences();\n");
    }
    out.push_str(
        "\x20       (Self { shell, demo: DemoState::new() }, Task::none())\n\
         \x20   }\n\
         }\n\
         \n",
    );

    // -- update() --------------------------------------------------------------
    out.push_str(
        "/// State transition function.\n\
         pub fn update(state: &mut AppState, message: Message) -> Task<Message> {\n\
         \x20   match message {\n\
         \x20       Message::Shell(msg) => match msg {\n\
         \x20           ShellMessage::ExecuteCommand(cmd_id) => execute_command(state, &cmd_id),\n\
         \x20           ShellMessage::SelectRibbonTab(tab_id) => {\n\
         \x20               state.shell.active_ribbon_tab = tab_id;\n",
    );
    push_persist(&mut out, spec);
    out.push_str(
        "\x20               Task::none()\n\
         \x20           }\n\
         \x20           ShellMessage::TogglePanel(panel_id) => {\n\
         \x20               state.shell.dock.toggle(&panel_id);\n",
    );
    push_persist(&mut out, spec);
    out.push_str(
        "\x20               Task::none()\n\
         \x20           }\n\
         \x20           ShellMessage::SelectBottomTab(tab_name) => {\n\
         \x20               state.shell.bottom_panel.active_tab = tab_name;\n",
    );
    push_persist(&mut out, spec);
    out.push_str(
        "\x20               Task::none()\n\
         \x20           }\n\
         \x20           ShellMessage::ToggleTheme => {\n\
         \x20               state.shell.theme = state.shell.theme.toggle();\n\
         \x20               state.demo.add_log(format!(\"[Theme] Switched to {} mode\", state.shell.theme.label()));\n",
    );
    push_persist(&mut out, spec);
    out.push_str(
        "\x20               Task::none()\n\
         \x20           }\n\
         \x20           ShellMessage::CloseAboutDialog => {\n\
         \x20               state.shell.show_about_dialog = false;\n\
         \x20               Task::none()\n\
         \x20           }\n\
         \x20           ShellMessage::SetStatusLeft(value) => {\n\
         \x20               state.shell.status_bar.left_text = value;\n\
         \x20               Task::none()\n\
         \x20           }\n\
         \x20           ShellMessage::SetStatusCenter(value) => {\n\
         \x20               state.shell.status_bar.center_text = value;\n\
         \x20               Task::none()\n\
         \x20           }\n\
         \x20           ShellMessage::SetStatusRight(value) => {\n\
         \x20               state.shell.status_bar.right_text = value;\n\
         \x20               Task::none()\n\
         \x20           }\n\
         \x20       },\n\
         \x20       Message::Demo(msg) => match msg {\n\
         \x20           DemoMessage::Select(name) => {\n\
         \x20               state.shell.status_bar.center_text = format!(\"Selected: {name}\");\n\
         \x20               state.demo.add_log(format!(\"[Selection] Activated stub item: {name}\"));\n\
         \x20               state.demo.selected = Some(name);\n\
         \x20               Task::none()\n\
         \x20           }\n\
         \x20           DemoMessage::ClearLogs => {\n\
         \x20               state.demo.logs.clear();\n\
         \x20               Task::none()\n\
         \x20           }\n\
         \x20       },\n\
         \x20       Message::Event(event, status) => {\n\
         \x20           if status == iced::event::Status::Ignored\n\
         \x20               && let Event::Keyboard(KeyboardEvent::KeyPressed { key, modifiers, .. }) = event\n\
         \x20               && let Some(cmd_id) = state.shell.commands.find_by_shortcut(&key, modifiers)\n\
         \x20           {\n\
         \x20               return execute_command(state, &cmd_id);\n\
         \x20           }\n\
         \x20           Task::none()\n\
         \x20       }\n\
         \x20   }\n\
         }\n\
         \n",
    );

    // -- execute_command() -------------------------------------------------------
    out.push_str(
        "/// Central command dispatch: every button, menu entry, toolbar item,\n\
         /// activity icon, ribbon item, and shortcut funnels through here.\n\
         fn execute_command(state: &mut AppState, cmd_id: &CommandId) -> Task<Message> {\n\
         \x20   match cmd_id.as_str() {\n\
         \x20       demo::APP_NEW => {\n\
         \x20           state.demo.add_log(\"[Command] New requested\".to_string());\n\
         \x20           state.shell.status_bar.left_text = \"New requested\".to_string();\n\
         \x20           Task::none()\n\
         \x20       }\n\
         \x20       demo::APP_QUIT => iced::exit(),\n\
         \x20       demo::HELP_ABOUT => {\n\
         \x20           state.shell.show_about_dialog = true;\n\
         \x20           Task::none()\n\
         \x20       }\n\
         \x20       demo::VIEW_TOGGLE_THEME => {\n\
         \x20           state.shell.theme = state.shell.theme.toggle();\n\
         \x20           state.demo.add_log(format!(\"[Theme] Switched to {} mode\", state.shell.theme.label()));\n",
    );
    push_persist(&mut out, spec);
    out.push_str(
        "\x20           Task::none()\n\
         \x20       }\n",
    );
    if has(spec, Feature::Explorer) {
        out.push_str(
            "\x20       demo::VIEW_TOGGLE_EXPLORER => {\n\
             \x20           state.shell.dock.toggle(&demo::LEFT_PANEL.into());\n",
        );
        push_persist(&mut out, spec);
        out.push_str("\x20           Task::none()\n\x20       }\n");
    }
    if has(spec, Feature::Inspector) {
        out.push_str(
            "\x20       demo::VIEW_TOGGLE_INSPECTOR => {\n\
             \x20           state.shell.dock.toggle(&demo::RIGHT_PANEL.into());\n",
        );
        push_persist(&mut out, spec);
        out.push_str("\x20           Task::none()\n\x20       }\n");
    }
    if has(spec, Feature::BottomPanel) {
        out.push_str(
            "\x20       demo::VIEW_TOGGLE_BOTTOM_PANEL => {\n\
             \x20           state.shell.dock.toggle(&demo::BOTTOM_PANEL.into());\n",
        );
        push_persist(&mut out, spec);
        out.push_str("\x20           Task::none()\n\x20       }\n");
    }
    out.push_str(
        "\x20       other => {\n\
         \x20           state.demo.add_log(format!(\"[Command] Unhandled command: {other}\"));\n\
         \x20           Task::none()\n\
         \x20       }\n\
         \x20   }\n\
         }\n\
         \n",
    );

    // -- view() ------------------------------------------------------------------
    out.push_str(
        "/// Declarative view: shell chrome around demo panel content.\n\
         pub fn view(state: &AppState) -> Element<'_, Message> {\n\
         \x20   let palette = state.shell.theme.palette();\n\
         \n\
         \x20   let mut stack = Column::new();\n",
    );
    if has(spec, Feature::Menu) {
        out.push_str(
            "\n\
             \x20   stack = stack.push(\n\
             \x20       desktop_shell::menu::view(demo::menu_items().as_slice(), palette).map(Message::Shell),\n\
             \x20   );\n",
        );
    }
    if has(spec, Feature::Ribbon) {
        out.push_str(
            "\n\
             \x20   stack = stack.push(\n\
             \x20       desktop_shell::ribbon::view::view(\n\
             \x20           &state.shell.ribbon_tabs,\n\
             \x20           &state.shell.active_ribbon_tab,\n\
             \x20           &state.shell.commands,\n\
             \x20           palette,\n\
             \x20       )\n\
             \x20       .map(Message::Shell),\n\
             \x20   );\n",
        );
    }
    if has(spec, Feature::Toolbar) {
        out.push_str(
            "\n\
             \x20   stack = stack.push(\n\
             \x20       desktop_shell::toolbar::view(demo::toolbar_items().as_slice(), palette)\n\
             \x20           .map(Message::Shell),\n\
             \x20   );\n",
        );
    }

    out.push_str(
        "\n\
         \x20   let mut middle = Row::new()\n\
         \x20       .width(Length::Fill)\n\
         \x20       .height(Length::Fill);\n",
    );
    if has(spec, Feature::ActivityBar) {
        out.push_str(
            "\n\
             \x20   {\n\
             \x20       let items = demo::activity_items();\n\
             \x20       let active = items.first().map(|item| item.id.as_str()).unwrap_or(\"\");\n\
             \x20       middle = middle.push(\n\
             \x20           desktop_shell::activity_bar::view(items.as_slice(), active, palette)\n\
             \x20               .map(Message::Shell),\n\
             \x20       );\n\
             \x20   }\n",
        );
    }
    if has(spec, Feature::Explorer) {
        out.push_str(
            "\n\
             \x20   if state.shell.dock.is_visible(&demo::LEFT_PANEL.into()) {\n\
             \x20       let content = demo::left_panel_content(&state.demo, palette);\n\
             \x20       middle = middle.push(desktop_shell::inspector::view(\n\
             \x20           demo::LEFT_TITLE,\n\
             \x20           content,\n\
             \x20           palette,\n\
             \x20           tokens::SIDEBAR_DEFAULT_WIDTH,\n\
             \x20           Some(ShellMessage::TogglePanel(demo::LEFT_PANEL.into())),\n\
             \x20       ));\n\
             \x20   }\n",
        );
    }
    out.push_str(
        "\n\
         \x20   middle = middle.push(\n\
         \x20       container(demo::workspace_view(&state.demo, palette))\n\
         \x20           .width(Length::Fill)\n\
         \x20           .height(Length::Fill),\n\
         \x20   );\n",
    );
    if has(spec, Feature::Inspector) {
        out.push_str(
            "\n\
             \x20   if state.shell.dock.is_visible(&demo::RIGHT_PANEL.into()) {\n\
             \x20       let content = demo::right_panel_content(&state.demo, palette);\n\
             \x20       middle = middle.push(desktop_shell::inspector::view(\n\
             \x20           demo::RIGHT_TITLE,\n\
             \x20           content,\n\
             \x20           palette,\n\
             \x20           tokens::INSPECTOR_DEFAULT_WIDTH,\n\
             \x20           Some(ShellMessage::TogglePanel(demo::RIGHT_PANEL.into())),\n\
             \x20       ));\n\
             \x20   }\n",
        );
    }
    out.push_str(
        "\n\
         \x20   let mut central = Column::new()\n\
         \x20       .width(Length::Fill)\n\
         \x20       .height(Length::Fill);\n\
         \x20   central = central.push(middle);\n",
    );
    if has(spec, Feature::BottomPanel) {
        out.push_str(
            "\n\
             \x20   if state.shell.dock.is_visible(&demo::BOTTOM_PANEL.into()) {\n\
             \x20       let content = demo::bottom_panel_content(&state.demo, palette);\n\
             \x20       central = central.push(desktop_shell::bottom_panel::view(\n\
             \x20           &state.shell.bottom_panel,\n\
             \x20           content,\n\
             \x20           palette,\n\
             \x20           tokens::BOTTOM_PANEL_DEFAULT_HEIGHT,\n\
             \x20           Some(ShellMessage::TogglePanel(demo::BOTTOM_PANEL.into())),\n\
             \x20       ));\n\
             \x20   }\n\
             \x20   stack = stack.push(central);\n",
        );
    } else {
        out.push_str("\x20   stack = stack.push(central);\n");
    }
    if has(spec, Feature::Statusbar) {
        out.push_str(
            "\n\
             \x20   stack = stack.push(desktop_shell::status_bar::view(&state.shell.status_bar, palette));\n",
        );
    }
    out.push_str(
        "\n\
         \x20   let base: Element<'_, Message> = stack\n\
         \x20       .width(Length::Fill)\n\
         \x20       .height(Length::Fill)\n\
         \x20       .into();\n\
         \n\
         \x20   if state.shell.show_about_dialog {\n\
         \x20       let dialog = container(\n\
         \x20           Column::new()\n\
         \x20               .align_x(Alignment::Center)\n\
         \x20               .spacing(tokens::SPACING_SM)\n\
         \x20               .padding(tokens::SPACING_LG)\n\
         \x20               .push(text(\"About \".to_string() + demo::APP_TITLE).size(tokens::FONT_SIZE_LG).color(palette.text_primary))\n\
         \x20               .push(\n\
         \x20                   text(\"Generated with the iced-desktop-shell scaffolder.\".to_string())\n\
         \x20                       .size(tokens::FONT_SIZE_SM)\n\
         \x20                       .color(palette.text_secondary),\n\
         \x20               )\n\
         \x20               .push(\n\
         \x20                   button(text(\"Close\").size(tokens::FONT_SIZE_SM))\n\
         \x20                       .padding([tokens::SPACING_XS, tokens::SPACING_LG])\n\
         \x20                       .on_press(Message::Shell(ShellMessage::CloseAboutDialog)),\n\
         \x20               ),\n\
         \x20       )\n\
         \x20       .width(380.0)\n\
         \x20       .style(move |_| iced::widget::container::Style {\n\
         \x20           background: Some(palette.surface.into()),\n\
         \x20           border: iced::border::Border {\n\
         \x20               color: palette.border,\n\
         \x20               width: 1.5,\n\
         \x20               radius: tokens::RADIUS_MD.into(),\n\
         \x20           },\n\
         \x20           ..Default::default()\n\
         \x20       });\n\
         \n\
         \x20       let overlay = container(dialog)\n\
         \x20           .width(Length::Fill)\n\
         \x20           .height(Length::Fill)\n\
         \x20           .center_x(Length::Fill)\n\
         \x20           .center_y(Length::Fill);\n\
         \n\
         \x20       iced::widget::stack![base, overlay].into()\n\
         \x20   } else {\n\
         \x20       base\n\
         \x20   }\n\
         }\n",
    );

    out
}

fn push_persist(out: &mut String, spec: &ResolvedSpec) {
    let stmt = persist_stmt(spec);
    if stmt.is_empty() {
        return;
    }
    out.push_str("\x20               ");
    out.push_str(stmt);
    out.push('\n');
}

// ---------------------------------------------------------------------------
// src/demo.rs (single file domain stub)
// ---------------------------------------------------------------------------

fn demo_widget_imports(spec: &ResolvedSpec) -> String {
    let mut names = BTreeSet::new();
    names.insert("column");
    names.insert("container");
    names.insert("text");
    if has(spec, Feature::Explorer) || has(spec, Feature::BottomPanel) {
        names.insert("button");
    }
    if has(spec, Feature::Inspector) {
        // right panel content is read-only text; nothing extra.
    }
    if has(spec, Feature::Explorer)
        || has(spec, Feature::Inspector)
        || has(spec, Feature::BottomPanel)
    {
        names.insert("scrollable");
    }
    if has(spec, Feature::Explorer) || has(spec, Feature::BottomPanel) {
        names.insert("Column");
    }
    if has(spec, Feature::BottomPanel) {
        names.insert("Space");
        names.insert("row");
    }
    let list: Vec<&str> = names.into_iter().collect();
    format!("use iced::widget::{{{}}};\n", list.join(", "))
}

fn demo_rs(spec: &ResolvedSpec) -> String {
    let mut out = String::new();
    let slots = spec.layout.slots();
    let left = slots.left.map(|s| (s.id, s.title));
    let right = slots.right.map(|s| (s.id, s.title));
    let bottom = slots.bottom.map(|s| (s.id, s.title));

    out.push_str(&format!(
        "//! {title} — replaceable domain stub (single file).\n\
         //!\n\
         //! Generated by the iced-desktop-shell scaffolder (layout: {layout},\n\
         //! features: {features}).\n\
         //! Owns demo commands, panel slot content, and workspace content. Replace\n\
         //! freely with real domain logic; `desktop-shell` never depends on anything\n\
         //! defined here.\n\
         \n\
         use crate::app::Message;\n\
         use desktop_shell::command::{{Command, CommandRegistry, Shortcut}};\n\
         use desktop_shell::theme::{{Palette, tokens}};\n\
         {widgets}\
         use iced::{{Alignment, Element, Length}};\n\
         \n",
        title = spec.app_title,
        layout = spec.layout.kebab(),
        features = spec.feature_list(),
        widgets = demo_widget_imports(spec),
    ));

    out.push_str(&format!(
        "/// Display name shared by the window title and the about dialog.\n\
         pub const APP_TITLE: &str = {title:?};\n\
         \n\
         /// Base commands, always registered.\n\
         pub const APP_NEW: &str = \"app.new\";\n\
         pub const APP_QUIT: &str = \"app.quit\";\n\
         pub const HELP_ABOUT: &str = \"help.about\";\n\
         pub const VIEW_TOGGLE_THEME: &str = \"view.toggle_theme\";\n",
        title = spec.app_title,
    ));
    if has(spec, Feature::Explorer) {
        out.push_str("pub const VIEW_TOGGLE_EXPLORER: &str = \"view.toggle_explorer\";\n");
    }
    if has(spec, Feature::Inspector) {
        out.push_str("pub const VIEW_TOGGLE_INSPECTOR: &str = \"view.toggle_inspector\";\n");
    }
    if has(spec, Feature::BottomPanel) {
        out.push_str("pub const VIEW_TOGGLE_BOTTOM_PANEL: &str = \"view.toggle_bottom_panel\";\n");
    }
    out.push('\n');

    if has(spec, Feature::Explorer) {
        let (id, title) = left.unwrap_or(("explorer", "Explorer"));
        out.push_str(&format!(
            "/// Left slot (feature `explorer` rendered through this preset's slot).\n\
             pub const LEFT_PANEL: &str = \"demo.{id}\";\n\
             pub const LEFT_TITLE: &str = {title:?};\n",
        ));
    }
    if has(spec, Feature::Inspector) {
        let (id, title) = right.unwrap_or(("inspector", "Inspector"));
        out.push_str(&format!(
            "/// Right slot (feature `inspector` rendered through this preset's slot).\n\
             pub const RIGHT_PANEL: &str = \"demo.{id}\";\n\
             pub const RIGHT_TITLE: &str = {title:?};\n",
        ));
    }
    if has(spec, Feature::BottomPanel) {
        let (id, title) = bottom.unwrap_or(("output", "Output"));
        out.push_str(&format!(
            "/// Bottom slot (feature `bottom-panel` rendered through this preset's slot).\n\
             pub const BOTTOM_PANEL: &str = \"demo.{id}\";\n\
             pub const BOTTOM_TITLE: &str = {title:?};\n",
        ));
    }
    out.push('\n');

    // -- state ---------------------------------------------------------------
    out.push_str(&format!(
        "/// Minimal demo state: selection plus a diagnostics log.\n\
         #[derive(Debug, Clone)]\n\
         pub struct DemoState {{\n\
         \x20   pub selected: Option<String>,\n\
         \x20   pub logs: Vec<String>,\n\
         }}\n\
         \n\
         impl DemoState {{\n\
         \x20   pub fn new() -> Self {{\n\
         \x20       Self {{\n\
         \x20           selected: None,\n\
         \x20           logs: vec![\"{title} ready.\".to_string()],\n\
         \x20       }}\n\
         \x20   }}\n\
         \n\
         \x20   pub fn add_log(&mut self, entry: impl Into<String>) {{\n\
         \x20       self.logs.push(entry.into());\n\
         \x20   }}\n\
         }}\n\
         \n\
         impl Default for DemoState {{\n\
         \x20   fn default() -> Self {{\n\
         \x20       Self::new()\n\
         \x20   }}\n\
         }}\n\
         \n\
         /// Demo actions.\n\
         #[derive(Debug, Clone)]\n\
         pub enum DemoMessage {{\n\
         \x20   Select(String),\n\
         \x20   ClearLogs,\n\
         }}\n\
         \n",
        title = spec.app_title,
    ));

    // -- commands ---------------------------------------------------------------
    out.push_str(
        "/// Register every command this stub exposes. Widgets only carry the\n\
         /// resulting `CommandId`; behavior lives in `app::execute_command`.\n\
         pub fn register_demo_commands(registry: &mut CommandRegistry) {\n\
         \x20   registry.register(\n\
         \x20       Command::new(APP_NEW, \"New\", \"Create a new project\")\n\
         \x20           .with_shortcut(Shortcut::ctrl('n'))\n\
         \x20           .with_icon(\"\\u{1f4c4}\"),\n\
         \x20   );\n\
         \x20   registry.register(\n\
         \x20       Command::new(APP_QUIT, \"Quit\", \"Exit the application\")\n\
         \x20           .with_shortcut(Shortcut::ctrl('q'))\n\
         \x20           .with_icon(\"\\u{1f6aa}\"),\n\
         \x20   );\n\
         \x20   registry.register(\n\
         \x20       Command::new(HELP_ABOUT, \"About\", \"Display application information\")\n\
         \x20           .with_icon(\"\\u{2139}\\u{fe0f}\"),\n\
         \x20   );\n\
         \x20   registry.register(\n\
         \x20       Command::new(VIEW_TOGGLE_THEME, \"Toggle Theme\", \"Switch between Dark and Light mode\")\n\
         \x20           .with_shortcut(Shortcut::ctrl('t'))\n\
         \x20           .with_icon(\"\\u{1f313}\"),\n\
         \x20   );\n",
    );
    if has(spec, Feature::Explorer) {
        out.push_str(
            "\x20   registry.register(\n\
             \x20       Command::new(VIEW_TOGGLE_EXPLORER, LEFT_TITLE, \"Toggle left panel visibility\")\n\
             \x20           .with_shortcut(Shortcut::ctrl('b'))\n\
             \x20           .with_icon(\"\\u{1f4c1}\"),\n\
             \x20   );\n",
        );
    }
    if has(spec, Feature::Inspector) {
        out.push_str(
            "\x20   registry.register(\n\
             \x20       Command::new(VIEW_TOGGLE_INSPECTOR, RIGHT_TITLE, \"Toggle right panel visibility\")\n\
             \x20           .with_shortcut(Shortcut::ctrl('i'))\n\
             \x20           .with_icon(\"\\u{1f50d}\"),\n\
             \x20   );\n",
        );
    }
    if has(spec, Feature::BottomPanel) {
        out.push_str(
            "\x20   registry.register(\n\
             \x20       Command::new(VIEW_TOGGLE_BOTTOM_PANEL, BOTTOM_TITLE, \"Toggle bottom panel visibility\")\n\
             \x20           .with_shortcut(Shortcut::ctrl('j'))\n\
             \x20           .with_icon(\"\\u{1f5a5}\\u{fe0f}\"),\n\
             \x20   );\n",
        );
    }
    out.push_str("}\n\n");

    // -- surfaces ---------------------------------------------------------------
    if has(spec, Feature::Menu) {
        out.push_str(
            "/// Menu bar entries: only commands registered above may appear here.\n\
             pub fn menu_items() -> Vec<desktop_shell::menu::MenuItem> {\n\
             \x20   vec![\n\
             \x20       desktop_shell::menu::MenuItem::new(\"File: New\", APP_NEW),\n",
        );
        if has(spec, Feature::Explorer) {
            out.push_str(
                "\x20       desktop_shell::menu::MenuItem::new(\"View: Left Panel\", VIEW_TOGGLE_EXPLORER),\n",
            );
        }
        if has(spec, Feature::Inspector) {
            out.push_str(
                "\x20       desktop_shell::menu::MenuItem::new(\"View: Right Panel\", VIEW_TOGGLE_INSPECTOR),\n",
            );
        }
        if has(spec, Feature::BottomPanel) {
            out.push_str(
                "\x20       desktop_shell::menu::MenuItem::new(\"View: Bottom Panel\", VIEW_TOGGLE_BOTTOM_PANEL),\n",
            );
        }
        out.push_str(
            "\x20       desktop_shell::menu::MenuItem::new(\"Theme\", VIEW_TOGGLE_THEME),\n\
             \x20       desktop_shell::menu::MenuItem::new(\"Help: About\", HELP_ABOUT),\n\
             \x20   ]\n\
             }\n\
             \n",
        );
    }

    if has(spec, Feature::Ribbon) {
        out.push_str(
            "/// Data-driven ribbon tabs: groups reference commands, never behavior.\n\
             pub fn ribbon_tabs() -> Vec<desktop_shell::ribbon::RibbonTab> {\n\
             \x20   use desktop_shell::ribbon::{RibbonGroup, RibbonItem, RibbonTab};\n\
             \n\
             \x20   let mut groups = vec![RibbonGroup::new(\n\
             \x20       \"Project\",\n\
             \x20       vec![RibbonItem::button(APP_NEW)],\n\
             \x20   )];\n",
        );
        let panel_buttons: Vec<String> = [
            (
                has(spec, Feature::Explorer),
                "RibbonItem::button(VIEW_TOGGLE_EXPLORER)",
            ),
            (
                has(spec, Feature::Inspector),
                "RibbonItem::button(VIEW_TOGGLE_INSPECTOR)",
            ),
            (
                has(spec, Feature::BottomPanel),
                "RibbonItem::button(VIEW_TOGGLE_BOTTOM_PANEL)",
            ),
        ]
        .into_iter()
        .filter(|(enabled, _)| *enabled)
        .map(|(_, code)| code.to_string())
        .collect();
        if !panel_buttons.is_empty() {
            out.push_str(&format!(
                "\n\
                 \x20   groups.push(RibbonGroup::new(\"Panels\", vec![{}]));\n",
                panel_buttons.join(", ")
            ));
        }
        out.push_str(
            "\n\
             \x20   groups.push(RibbonGroup::new(\n\
             \x20       \"Appearance\",\n\
             \x20       vec![RibbonItem::button(VIEW_TOGGLE_THEME)],\n\
             \x20   ));\n\
             \x20   groups.push(RibbonGroup::new(\n\
             \x20       \"Help\",\n\
             \x20       vec![RibbonItem::button(HELP_ABOUT)],\n\
             \x20   ));\n\
             \n\
             \x20   vec![RibbonTab::new(\"home\", \"Home\", groups)]\n\
             }\n\
             \n",
        );
    }

    if has(spec, Feature::ActivityBar) {
        out.push_str(
            "/// Activity rail entries: icon plus command, no domain meaning attached.\n\
             pub fn activity_items() -> Vec<desktop_shell::activity_bar::ActivityItem> {\n\
             \x20   use desktop_shell::activity_bar::ActivityItem;\n\
             \n\
             \x20   vec![\n",
        );
        if has(spec, Feature::Explorer) {
            out.push_str(
                "\x20       ActivityItem::new(LEFT_PANEL, \"\\u{1f4c1}\", VIEW_TOGGLE_EXPLORER),\n",
            );
        }
        out.push_str(
            "\x20       ActivityItem::new(\"theme\", \"\\u{1f313}\", VIEW_TOGGLE_THEME),\n\
             \x20       ActivityItem::new(\"about\", \"\\u{2139}\\u{fe0f}\", HELP_ABOUT),\n\
             \x20   ]\n\
             }\n\
             \n",
        );
    }

    if has(spec, Feature::Toolbar) {
        out.push_str(
            "/// Compact toolbar strip: icon plus label per command.\n\
             pub fn toolbar_items() -> Vec<desktop_shell::toolbar::ToolbarItem> {\n\
             \x20   use desktop_shell::toolbar::ToolbarItem;\n\
             \n\
             \x20   vec![\n\
             \x20       ToolbarItem::new(\"new\", APP_NEW)\n\
             \x20           .with_label(\"New\")\n\
             \x20           .with_icon(\"\\u{1f4c4}\"),\n",
        );
        if has(spec, Feature::Explorer) {
            out.push_str(
                "\x20       ToolbarItem::new(\"left-panel\", VIEW_TOGGLE_EXPLORER).with_label(LEFT_TITLE),\n",
            );
        }
        if has(spec, Feature::Inspector) {
            out.push_str(
                "\x20       ToolbarItem::new(\"right-panel\", VIEW_TOGGLE_INSPECTOR).with_label(RIGHT_TITLE),\n",
            );
        }
        if has(spec, Feature::BottomPanel) {
            out.push_str(
                "\x20       ToolbarItem::new(\"bottom-panel\", VIEW_TOGGLE_BOTTOM_PANEL).with_label(BOTTOM_TITLE),\n",
            );
        }
        out.push_str(
            "\x20       ToolbarItem::new(\"theme\", VIEW_TOGGLE_THEME).with_label(\"Theme\"),\n\
             \x20   ]\n\
             }\n\
             \n",
        );
    }

    if has(spec, Feature::Explorer) {
        out.push_str(
            "/// Left panel stub: selectable placeholder items driving `DemoMessage::Select`.\n\
             pub fn left_panel_content(state: &DemoState, palette: Palette) -> Element<'_, Message> {\n\
             \x20   let mut items = Column::new()\n\
             \x20       .spacing(tokens::SPACING_XS)\n\
             \x20       .padding(tokens::SPACING_SM);\n\
             \n\
             \x20   for item in [\"Item A\", \"Item B\", \"Item C\"] {\n\
             \x20       let active = state.selected.as_deref() == Some(item);\n\
             \x20       let label = if active {\n\
             \x20           format!(\"\\u{25cf} {item}\")\n\
             \x20       } else {\n\
             \x20           format!(\"\\u{25cb} {item}\")\n\
             \x20       };\n\
             \x20       items = items.push(\n\
             \x20           button(text(label).size(tokens::FONT_SIZE_SM).color(palette.text_primary))\n\
             \x20               .width(Length::Fill)\n\
             \x20               .padding([tokens::SPACING_XS, tokens::SPACING_SM])\n\
             \x20               .on_press(Message::Demo(DemoMessage::Select(item.to_string())))\n\
             \x20               .style(move |_theme, status| {\n\
             \x20                   let bg = if active {\n\
             \x20                       palette.surface_active\n\
             \x20                   } else if status == iced::widget::button::Status::Hovered {\n\
             \x20                       palette.surface_hover\n\
             \x20                   } else {\n\
             \x20                       palette.surface\n\
             \x20                   };\n\
             \x20                   iced::widget::button::Style {\n\
             \x20                       background: Some(bg.into()),\n\
             \x20                       text_color: palette.text_primary,\n\
             \x20                       border: iced::border::Border::default(),\n\
             \x20                       ..Default::default()\n\
             \x20                   }\n\
             \x20               }),\n\
             \x20       );\n\
             \x20   }\n\
             \n\
             \x20   scrollable(items)\n\
             \x20       .width(Length::Fill)\n\
             \x20       .height(Length::Fill)\n\
             \x20       .into()\n\
             }\n\
             \n",
        );
    }

    if has(spec, Feature::Inspector) {
        out.push_str(
            "/// Right panel stub: read-only properties of the current selection.\n\
             pub fn right_panel_content(state: &DemoState, palette: Palette) -> Element<'_, Message> {\n\
             \x20   let name = state.selected.as_deref().unwrap_or(\"No selection\");\n\
             \n\
             \x20   scrollable(\n\
             \x20       column![\n\
             \x20           text(name).size(tokens::FONT_SIZE_SM).color(palette.text_primary),\n\
             \x20           text(\"Kind: stub entity\").size(tokens::FONT_SIZE_XS).color(palette.text_secondary),\n\
             \x20           text(\"Status: ready\").size(tokens::FONT_SIZE_XS).color(palette.text_secondary),\n\
             \x20       ]\n\
             \x20       .spacing(tokens::SPACING_XS)\n\
             \x20       .padding(tokens::SPACING_SM),\n\
             \x20   )\n\
             \x20   .width(Length::Fill)\n\
             \x20   .height(Length::Fill)\n\
             \x20   .into()\n\
             }\n\
             \n",
        );
    }

    if has(spec, Feature::BottomPanel) {
        out.push_str(
            "/// Bottom panel stub: diagnostics log with a clear action.\n\
             pub fn bottom_panel_content(state: &DemoState, palette: Palette) -> Element<'_, Message> {\n\
             \x20   let mut logs = Column::new()\n\
             \x20       .spacing(tokens::SPACING_XXS)\n\
             \x20       .padding(tokens::SPACING_SM);\n\
             \n\
             \x20   for log in &state.logs {\n\
             \x20       logs = logs.push(text(log).size(tokens::FONT_SIZE_XS).color(palette.text_secondary));\n\
             \x20   }\n\
             \n\
             \x20   let bar = row![\n\
             \x20       text(format!(\"Entries: {}\", state.logs.len()))\n\
             \x20           .size(tokens::FONT_SIZE_XS)\n\
             \x20           .color(palette.text_muted),\n\
             \x20       Space::new().width(Length::Fill),\n\
             \x20       button(text(\"Clear\").size(tokens::FONT_SIZE_XS))\n\
             \x20           .padding([tokens::SPACING_XXS, tokens::SPACING_SM])\n\
             \x20           .on_press(Message::Demo(DemoMessage::ClearLogs)),\n\
             \x20   ]\n\
             \x20   .align_y(Alignment::Center)\n\
             \x20   .padding([tokens::SPACING_XXS, tokens::SPACING_SM]);\n\
             \n\
             \x20   column![\n\
             \x20       bar,\n\
             \x20       scrollable(logs).width(Length::Fill).height(Length::Fill),\n\
             \x20   ]\n\
             \x20   .width(Length::Fill)\n\
             \x20   .height(Length::Fill)\n\
             \x20   .into()\n\
             }\n\
             \n",
        );
    }

    // -- workspace (always) ------------------------------------------------------
    out.push_str(&format!(
        "/// Central workspace stub: replace with the real canvas, dashboard, or editor.\n\
         pub fn workspace_view(state: &DemoState, palette: Palette) -> Element<'_, Message> {{\n\
         \x20   let selected = state.selected.as_deref().unwrap_or(\"nothing\");\n\
         \n\
         \x20   let body = column![\n\
         \x20       text(APP_TITLE).size(tokens::FONT_SIZE_LG).color(palette.text_primary),\n\
         \x20       text(\"Layout: {layout} — replace this stub with real workspace content.\")\n\
         \x20           .size(tokens::FONT_SIZE_SM)\n\
         \x20           .color(palette.text_secondary),\n\
         \x20       text(format!(\"Selected: {{selected}}\"))\n\
         \x20           .size(tokens::FONT_SIZE_SM)\n\
         \x20           .color(palette.accent),\n\
         \x20   ]\n\
         \x20   .spacing(tokens::SPACING_SM)\n\
         \x20   .align_x(Alignment::Center);\n\
         \n\
         \x20   container(body)\n\
         \x20       .center_x(Length::Fill)\n\
         \x20       .center_y(Length::Fill)\n\
         \x20       .width(Length::Fill)\n\
         \x20       .height(Length::Fill)\n\
         \x20       .into()\n\
         }}\n",
        layout = spec.layout.kebab(),
    ));

    out
}

// ---------------------------------------------------------------------------
// metadata + docs
// ---------------------------------------------------------------------------

fn scaffold_toml(spec: &ResolvedSpec) -> String {
    let features = spec
        .features
        .iter()
        .map(|feature| format!("    \"{}\",", feature.kebab()))
        .collect::<Vec<_>>()
        .join("\n");
    format!(
        "# Generated by the iced-desktop-shell scaffolder.\n\
         # Informative metadata only: this file is NOT a second source of truth.\n\
         # Manual edits to the project do not require updating it, and the\n\
         # generator never reads it back.\n\
         \n\
         [project]\n\
         name = \"{crate_name}\"\n\
         layout = \"{layout}\"\n\
         theme = \"{theme}\"\n\
         \n\
         features = [\n\
         {features}\n\
         ]\n",
        crate_name = spec.crate_name,
        layout = spec.layout.kebab(),
        theme = spec.theme.kebab(),
        features = features,
    )
}

fn agents_md(spec: &ResolvedSpec) -> String {
    let mut panels = String::new();
    if has(spec, Feature::Explorer) {
        panels.push_str("- Left panel slot `demo::LEFT_PANEL` (`demo::LEFT_TITLE`) in `src/demo.rs` (`left_panel_content`).\n");
    }
    if has(spec, Feature::Inspector) {
        panels.push_str("- Right panel slot `demo::RIGHT_PANEL` (`demo::RIGHT_TITLE`) in `src/demo.rs` (`right_panel_content`).\n");
    }
    if has(spec, Feature::BottomPanel) {
        panels.push_str("- Bottom panel slot `demo::BOTTOM_PANEL` (`demo::BOTTOM_TITLE`) in `src/demo.rs` (`bottom_panel_content`).\n");
    }
    if panels.is_empty() {
        panels.push_str("- No side/bottom panels in this configuration; add slots in `src/demo.rs` and register them in `src/app.rs`.\n");
    }
    let persistence = if has(spec, Feature::Persistence) {
        "Persistence is enabled: `AppState::new` loads `ShellPreferences` and mutations call `request_save_preferences()`."
    } else {
        "Persistence is disabled: add feature `persistence` at generation time (or wire `ShellPreferences` manually) to keep theme and panel visibility across restarts."
    };
    format!(
        "# AGENTS.md — {title}\n\
         \n\
         > Generated by the iced-desktop-shell scaffolder (layout `{layout}`, theme `{theme}`).\n\
         > This is normal, editable application code; the generator is not needed to develop it.\n\
         \n\
         ## Layout and features\n\
         \n\
         - Layout: `{layout}`\n\
         - Features: {features}\n\
         - Theme default: `{theme}`\n\
         \n\
         ## Where things live\n\
         \n\
         - Domain logic: `src/demo.rs` (commands, panel content, workspace content). Replace freely.\n\
         - Reusable shell: the `desktop-shell` dependency (commands, dock, ribbon, theme, persistence). Do not fork it; depend on it.\n\
         - Orchestration: `src/app.rs` (`AppState`, `Message`, `update`, `view`). Routes shell and demo messages and dispatches commands.\n\
         - Commands: register in `register_demo_commands()` (`src/demo.rs`), handle in `execute_command()` (`src/app.rs`). Widgets only carry `CommandId`.\n\
         - Panels:\n\
         {panels}\
         - Workspace: `workspace_view()` in `src/demo.rs`.\n\
         \n\
         ## Rules\n\
         \n\
         - Never put domain logic into `desktop-shell`; keep it in `src/demo.rs` (or new domain modules).\n\
         - Widgets must emit `CommandId` (or `DemoMessage`) — never trigger side effects directly.\n\
         - Reuse shell design tokens; do not disperse magic numbers.\n\
         - {persistence}\n\
         \n\
         ## Generation metadata\n\
         \n\
         See `.scaffold.toml` (informative only, not a source of truth).\n",
        title = spec.app_title,
        layout = spec.layout.kebab(),
        theme = spec.theme.kebab(),
        features = spec.feature_list(),
        panels = panels,
        persistence = persistence,
    )
}

fn readme_md(spec: &ResolvedSpec) -> String {
    format!(
        "# {title}\n\
         \n\
         > Technical desktop application generated with the [iced-desktop-shell]({git}) scaffolder\n\
         > (layout `{layout}`, theme `{theme}`, features: {features}).\n\
         \n\
         ## Running\n\
         \n\
         ```bash\n\
         cargo run\n\
         ```\n\
         \n\
         Requires a graphical session (X11 or Wayland) and, on Debian/Ubuntu, the\n\
         system libraries for Iced: `libxkbcommon-dev libwayland-dev libasound2-dev libfontconfig1-dev`.\n\
         \n\
         ## Structure\n\
         \n\
         ```text\n\
         src/main.rs   # Iced runner\n\
         src/app.rs    # AppState / Message / update / view (orchestrator)\n\
         src/demo.rs   # Replaceable domain stub (commands, panels, workspace)\n\
         .scaffold.toml# Generation metadata (informative only)\n\
         ```\n\
         \n\
         ## Next steps\n\
         \n\
         Replace `src/demo.rs` with real domain logic. See `AGENTS.md` for the map.\n",
        title = spec.app_title,
        git = SHELL_GIT_URL,
        layout = spec.layout.kebab(),
        theme = spec.theme.kebab(),
        features = spec.feature_list(),
    )
}
